"""conexion tabla usersypost

Revision ID: 066ffe58c6bb
Revises: 7223c4250365
Create Date: 2023-08-03 21:54:18.558277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066ffe58c6bb'
down_revision = '7223c4250365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Post')
    # ### end Alembic commands ###
